### ISSUE TITLE
Please add domains from temporarymail.com

### ISSUE THREAD

**Issue by ToX82** [andimg93/DisposableMailDetection#1]
Could you please add the following domains?

`appmailer.org`
`basicmail.host`
`easyonlinemail.net`
`incorporatedmail.com`
`ultramailinator.com`

Those are all used by https://temporarymail.com

**Comment by andimg93** [comment]
Thank you for your request with already suggested additions. I have considered these as part of a further update, which brings the number of entries to almost 138k so far.

See tag 1.1.10 in comparison with 1.1.11:
https://github.com/andimg93/DisposableMailDetection/compare/1.1.10...1.1.11

I therefore close the issue 😉.
